[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Tyler Park <tyler.park@fortemtech.com>"]

[dependencies]

[lib]
name = "aoclib"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"