[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Tyler Park <tyler.park@fortemtech.com>"]
edition = "2018"

[dependencies]
itertools = "~0.7.8"
log = "~0.4"
env_logger = "~0.8"

[[bin]]
name = "main"
path = "src/main.rs"